#!/usr/bin/env node
// static/data/{a2la,jab}-scopes.md → seed/scopes.sql
//
//   使い方:  node scripts/seed-from-md.mjs            # seed/scopes.sql を生成
//            npm run db:seed                          # 生成 + 本番 D1 へ投入
//            npm run db:seed:local                    # 生成 + ローカル D1 へ投入
//
// 生成される SQL は何度実行しても安全（冪等）:
//   - 同じ内容（同じハッシュ）の MD は二重登録されない
//   - 内容が変わった MD は新しい certificates 行として追加され、古い行は is_current = 0 になる

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { parseScopesDocument } from '../src/lib/md.js';
import { extractStandardCore } from '../src/lib/matcher.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const q = v => (v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const CHUNK = 40; // 1 INSERT あたりの行数（D1 のパラメータ/ステートメント長制限に余裕を持たせる）

const now = new Date().toISOString();
const sql = [];
sql.push(`-- generated by scripts/seed-from-md.mjs at ${now}`);
sql.push(`PRAGMA foreign_keys = ON;`);

for (const certType of ['a2la', 'jab']) {
  const rel = `static/data/${certType}-scopes.md`;
  const md = readFileSync(join(root, rel), 'utf8');
  const hash = createHash('sha256').update(md).digest('hex');
  const doc = parseScopesDocument(md, certType);
  const { certificate_number, organization, accreditation_body, valid_until, accreditation_standard, ...extra } = doc.info;

  sql.push('');
  sql.push(`-- ===== ${certType.toUpperCase()}  ${rel}  items=${doc.items.length} facilities=${doc.facilities.length} hash=${hash.slice(0, 12)}`);
  // 1) 未登録ならヘッダ行を追加
  sql.push(`INSERT INTO certificates (cert_type, certificate_number, organization, accreditation_body, valid_until, accreditation_standard, extra_info, source_file, source_hash, imported_at, is_current)
SELECT ${q(certType)}, ${q(certificate_number)}, ${q(organization)}, ${q(accreditation_body)}, ${q(valid_until)}, ${q(accreditation_standard)}, ${q(JSON.stringify(extra))}, ${q(rel)}, ${q(hash)}, ${q(now)}, 1
WHERE NOT EXISTS (SELECT 1 FROM certificates WHERE cert_type = ${q(certType)} AND source_hash = ${q(hash)});`);
  // 2) この内容を current にし、他を過去扱いに
  sql.push(`UPDATE certificates SET is_current = 0 WHERE cert_type = ${q(certType)} AND source_hash <> ${q(hash)};`);
  sql.push(`UPDATE certificates SET is_current = 1 WHERE cert_type = ${q(certType)} AND source_hash = ${q(hash)};`);
  // 3) 明細は毎回作り直す（冪等）
  const certSel = `(SELECT id FROM certificates WHERE cert_type = ${q(certType)} AND source_hash = ${q(hash)})`;
  sql.push(`DELETE FROM scope_items WHERE certificate_id = ${certSel};`);
  sql.push(`DELETE FROM facilities  WHERE certificate_id = ${certSel};`);

  for (const f of doc.facilities) {
    sql.push(`INSERT INTO facilities (certificate_id, facility_number, name, location, anchor) VALUES (${certSel}, ${q(f.facility_number)}, ${q(f.name)}, ${q(f.location)}, ${q(f.anchor)});`);
  }
  const facSel = n => (n ? `(SELECT id FROM facilities WHERE certificate_id = ${certSel} AND facility_number = ${q(n)})` : 'NULL');

  for (let i = 0; i < doc.items.length; i += CHUNK) {
    const rows = doc.items.slice(i, i + CHUNK).map(it =>
      `(${certSel}, ${facSel(it.facility_number)}, ${q(it.category)}, ${q(it.anchor)}, ${q(it.standard)}, ${q(it.description)}, ${q(extractStandardCore(it.standard))}, ${it.sort_order})`
    );
    sql.push(`INSERT INTO scope_items (certificate_id, facility_id, category, anchor, standard, description, core, sort_order) VALUES\n${rows.join(',\n')};`);
  }
  console.log(`${certType.padEnd(5)} ${rel}: ${doc.items.length} items, ${doc.facilities.length} facilities, hash ${hash.slice(0, 12)}…`);
}

mkdirSync(join(root, 'seed'), { recursive: true });
const out = join(root, 'seed', 'scopes.sql');
writeFileSync(out, sql.join('\n') + '\n');
console.log(`→ ${out} (${(sql.join('\n').length / 1024).toFixed(0)} KB)`);
